name: snp_chatbot
description: Ứng dụng SNP Chatbot (Chat/FAQ/Tasks/Admin) với dữ liệu online + cache offline
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  http: ^1.2.2
  path_provider: ^2.1.4

  # Notifications + timezone cho lịch
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/config.json
    - assets/faq_public.json
    - assets/faq_internal.json
    - assets/employees.json
    - assets/tasks.json
