name: snp_mobile
description: SNP Chatbot demo (clean skeleton, CI-ready)
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  path_provider: ^2.1.5
  timezone: ^0.9.4
  flutter_local_notifications: ^17.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  # Nếu bạn có assets, bật khối này và tạo thư mục assets/
  # assets:
  #   - assets/

  # Nếu bạn có fonts custom, bật khối này
  # fonts:
  #   - family: MyFont
  #     fonts:
  #       - asset: assets/fonts/MyFont-Regular.ttf
