name: snp_chatbot
description: "SNP Chatbot demo - minimal buildable app"
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

# KHÔNG dùng gói ngoài để tránh lỗi build Android
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/faq_public.json
    - assets/faq_internal.json
