name: build-android

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # dùng kênh stable mới nhất; nếu bạn muốn pin version, điền ví dụ: '3.22.2'
          channel: "stable"

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Get Flutter dependencies
        run: flutter pub get
        working-directory: app_lib

      - name: Build APK (release)
        run: flutter build apk --release
        working-directory: app_lib

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app_lib/build/app/outputs/flutter-apk/app-release.apk
