name: build-android

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter (pin 3.10.6 để tương thích v1)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.6"

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Show Flutter/Dart versions
        run: |
          flutter --version
          dart --version

      - name: Get Flutter dependencies
        run: flutter pub get
        working-directory: app_lib

      - name: List direct dependencies (để khoanh vùng plugin v1)
        run: |
          echo "--------- pubspec.yaml ---------"
          cat pubspec.yaml
          echo "--------- deps (compact) --------"
          flutter pub deps --style=compact
        working-directory: app_lib

      - name: Build APK (release)
        run: |
          flutter clean
          flutter build apk --release
        working-directory: app_lib

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app_lib/build/app/outputs/flutter-apk/app-release.apk
