name: build-android

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Flutter 3.19.6 đi cùng Dart 3.3.x (hợp lệ với SDK >=3.3.0 <4.0.0)
      - name: Set up Flutter (3.19.6)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Versions
        run: |
          flutter --version
          dart --version

      # Kiểm tra không còn dấu vết embedding v1
      - name: Sanity check (no v1 embedding remnants)
        run: |
          if grep -R -nE "io\.flutter\.app\.Flutter(Application|Activity)|GeneratedPluginRegistrant|\$\{applicationName\}" app_lib/android ; then
            echo "❌ Vẫn còn dấu vết v1 trong android/. Vui lòng xoá theo hướng dẫn."; exit 1;
          else
            echo "✅ Không còn v1 remnants trong android/"; 
          fi

      - name: Get Flutter dependencies
        run: flutter pub get
        working-directory: app_lib

      - name: Build APK (release)
        run: |
          flutter clean
          flutter build apk --release
        working-directory: app_lib

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app_lib/build/app/outputs/flutter-apk/app-release.apk
