name: Build Android (Flutter)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter (stable 3.35.3)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.3"
          channel: "stable"
          cache: true

      - name: Flutter doctor (env check)
        run: flutter doctor -v

      # Chấp nhận license Android trên runner
      - name: Accept Android licenses
        run: yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: flutter pub get
        working-directory: app_lib
        run: flutter pub get

      - name: Build APK (release, verbose)
        working-directory: app_lib
        run: flutter build apk --release --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app_lib/build/app/outputs/flutter-apk/app-release.apk
