name: build-android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter (stable 3.35.x)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.2'

      # Làm việc trong thư mục gốc của app Flutter (app_lib)
      - name: Flutter version
        working-directory: app_lib
        run: flutter --version

      - name: Get dependencies
        working-directory: app_lib
        run: flutter pub get

      # Chấp nhận license Android SDK (để tránh lỗi AAR metadata v.v.)
      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      # Build APK release bằng Flutter (không gọi gradlew)
      - name: Build APK (release)
        working-directory: app_lib
        # nếu app entry khác lib/main.dart thì đổi lại --target tương ứng
        run: flutter build apk --release --target=lib/main.dart

      # Upload artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app_lib/build/app/outputs/flutter-apk/app-release.apk
