name: Build Android (Flutter)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Toàn bộ lệnh sẽ chạy trong thư mục app_lib (nơi chứa pubspec.yaml & android/)
    defaults:
      run:
        working-directory: app_lib

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-34
            build-tools;34.0.0
            platform-tools

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # Nếu dự án của bạn dùng version khác, sửa đúng số vào đây.
          flutter-version: "3.19.6"
          channel: "stable"
          cache: true

      - name: Flutter doctor (sanity check)
        run: flutter --version

      - name: Flutter pub get
        run: flutter pub get

      # Bảo đảm gradlew trong android/ có quyền thực thi (tránh Permission denied)
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app_lib/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
