name: Build Android (Flutter)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app_lib

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          ndk: "27.0.12077973" # optional, không hại gì

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.35.3"

      - name: Flutter doctor (diagnose)
        run: flutter doctor -v

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK (release, Flutter)
        run: flutter build apk --release -v

      # Fallback: ép Gradle build module :app (nếu vì lý do nào đó lệnh trên không tạo ra APK)
      - name: Build APK via Gradle (fallback)
        run: |
          chmod +x android/gradlew
          ./android/gradlew -p android :app:assembleRelease --stacktrace --info || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: snp-chatbot-apk
          path: |
            app/build/outputs/flutter-apk/*.apk
            android/app/build/outputs/apk/release/*.apk
          if-no-files-found: warn
