name: build-android

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'   # giữ đúng version bạn đang dùng
          channel: 'stable'

      - name: Flutter version
        run: flutter --version

      - name: Get dependencies
        working-directory: app_lib
        run: flutter pub get

      - name: Build APK (release)
        working-directory: app_lib
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app_lib/build/app/outputs/flutter-apk/app-release.apk
