      # Build APK (Flutter) + fallback Gradle, và in log chi tiết
      - name: Build APK (release, verbose + fallback)
        working-directory: app_lib
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
        run: |
          set -e
          echo "== flutter clean =="
          flutter clean

          echo "== flutter build apk --release -v =="
          # Không dừng job ngay nếu lệnh thất bại để còn chạy fallback
          set +e
          flutter build apk --release -v
          FLUTTER_RC=$?
          set -e

          echo "== Liệt kê outputs sau flutter build =="
          ls -R build/app/outputs || true

          # Chuẩn vị trí Flutter mới
          APK_STD="build/app/outputs/flutter-apk/app-release.apk"

          # Nếu chưa thấy, chạy Gradle trực tiếp để lấy log rõ ràng
          if [ ! -f "$APK_STD" ]; then
            echo "== Chưa thấy APK chuẩn. Chạy Gradle fallback với stacktrace… =="
            pushd android
            ./gradlew :app:assembleRelease --stacktrace --warning-mode all --info
            popd
          fi

          echo "== Tìm APK ở mọi nơi trong app_lib =="
          FOUND=$(ls -1 **/*.apk 2>/dev/null | head -n 1 || true)
          if [ -z "$FOUND" ]; then
            echo "❌ Không tìm thấy file APK sau cả Flutter và Gradle."
            echo "Gợi ý: kiểm tra module name phải là :app và productFlavors (nếu có)."
            exit 1
          fi

          echo "✅ Tìm thấy APK: $FOUND"
          mkdir -p build/app/outputs/flutter-apk
          cp "$FOUND" "$APK_STD"
          echo "== Vị trí chuẩn hóa: $APK_STD =="

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: snp-chatbot-apk
          path: app_lib/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
