name: Build Android (Flutter)

on:
  workflow_dispatch: # Cho phép run thủ công
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app_lib  # <<-- Đảm bảo chạy trong app_lib

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.6  # Khớp với máy bạn

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: SNP-Chatbot-APK
          path: app_lib/build/app/outputs/flutter-apk/app-release.apk
