name: build-android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Toàn bộ lệnh mặc định chạy trong thư mục app_lib (thư mục Flutter)
    defaults:
      run:
        working-directory: app_lib

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.2'

      - name: Flutter version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      # Chạy trong module Android để đảm bảo gradlew có quyền thực thi
      - name: Make gradlew executable
        run: |
          cd android
          chmod +x gradlew
          ./gradlew --version

      # Chấp nhận license SDK (không fail nếu thiếu path)
      - name: Accept Android licenses
        run: |
          yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --licenses || true

      # Build APK bằng Flutter (đã đọc đúng android/app/build.gradle)
      - name: Build APK (release)
        run: flutter build apk --release

      # Upload artifact: Flutter để output ở build/app/outputs/flutter-apk/
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app_lib/build/app/outputs/flutter-apk/app-release.apk
