      - name: Build APK (release, verbose + fallback)
        working-directory: app_lib
        shell: bash
        run: |
          set -e
          flutter clean
          flutter build apk --release -v --target=lib/main.dart || true

          echo "== Liệt kê outputs sau flutter build =="
          ls -la build/app/outputs || true

          APK_PATH=""
          if [ -f build/app/outputs/flutter-apk/app-release.apk ]; then
            APK_PATH="build/app/outputs/flutter-apk/app-release.apk"
          elif [ -f build/app/outputs/apk/release/app-release.apk ]; then
            APK_PATH="build/app/outputs/apk/release/app-release.apk"
          fi

          if [ -z "$APK_PATH" ]; then
            echo "== Chưa thấy APK chuẩn. Chạy Gradle fallback… =="

            # ✅ FIX quyền + dòng xuống dòng CRLF
            sed -i 's/\r$//' android/gradlew
            chmod +x android/gradlew

            pushd android
            ./gradlew :app:assembleRelease --stacktrace --info
            popd

            if [ -f android/app/build/outputs/apk/release/app-release.apk ]; then
              APK_PATH="android/app/build/outputs/apk/release/app-release.apk"
            fi
          fi

          if [ -z "$APK_PATH" ]; then
            echo "❌ Không tìm thấy file APK sau cả Flutter và Gradle."
            exit 1
          fi

          echo "✅ Tìm thấy APK: $APK_PATH"
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
