name: Build Android (Flutter)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.3" # theo log của bạn

      - name: Flutter doctor (quick)
        run: flutter --version

      - name: Get packages
        working-directory: app_lib
        run: flutter pub get

      - name: Build APK (release, verbose + fallback)
        working-directory: app_lib
        shell: bash
        run: |
          set -e
          flutter clean
          # build flutter trước
          flutter build apk --release -v --target=lib/main.dart || true

          echo "== Liệt kê outputs sau flutter build =="
          ls -la build/app/outputs || true

          APK_PATH=""
          if [ -f build/app/outputs/flutter-apk/app-release.apk ]; then
            APK_PATH="build/app/outputs/flutter-apk/app-release.apk"
          elif [ -f build/app/outputs/apk/release/app-release.apk ]; then
            APK_PATH="build/app/outputs/apk/release/app-release.apk"
          fi

          if [ -z "$APK_PATH" ]; then
            echo "== Chưa thấy APK chuẩn. Chạy Gradle fallback… =="
            cd android
            ./gradlew :app:assembleRelease --stacktrace --info
            cd ..
            if [ -f android/app/build/outputs/apk/release/app-release.apk ]; then
              APK_PATH="android/app/build/outputs/apk/release/app-release.apk"
            fi
          fi

          if [ -z "$APK_PATH" ]; then
            echo "❌ Không tìm thấy file APK sau cả Flutter và Gradle."
            exit 1
          fi

          echo "✅ Tìm thấy APK: $APK_PATH"
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app_lib/${{ env.APK_PATH }}
