name: Build Android APK (SNP Chatbot)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'

      # Tạo project Flutter trống tên "mobile"
      - name: Create Flutter project
        run: flutter create mobile

      # Chép code Dart của bạn (đang ở root repo) vào mobile/lib
      - name: Copy app code
        run: |
          rm -rf mobile/lib/*
          mkdir -p mobile/lib
          cp main.dart mobile/lib/
          cp login_screen.dart mobile/lib/
          cp chat_screen.dart mobile/lib/
          cp qa_service.dart mobile/lib/

      # Chép dữ liệu FAQ vào assets
      - name: Copy FAQ assets
        run: |
          mkdir -p mobile/assets
          cp faq_public.json mobile/assets/
          cp faq_internal.json mobile/assets/

      # Khai báo assets trong pubspec.yaml
      - name: Enable assets in pubspec
        run: |
          awk '1;/flutter:/{print "  assets:\n    - assets/"; exit}' mobile/pubspec.yaml > /tmp/pubspec.yaml
          cat /tmp/pubspec.yaml > mobile/pubspec.yaml

      # Cài dependency (nếu sau này bạn cần package khác, thêm vào pubspec.yaml trước bước này)
      - name: Flutter pub get
        working-directory: mobile
        run: flutter pub get

      # Build APK release
      - name: Build APK (release)
        working-directory: mobile
        run: flutter build apk --release

      # Upload file APK (dùng v4 mới, tránh lỗi deprecated)
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: snp-chatbot-apk
          path: mobile/build/app/outputs/flutter-apk/app-release.apk
