name: Build Android APK (SNP Chatbot)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'

      # Tạo project Flutter trống tên "mobile"
      - name: Create Flutter project
        run: flutter create mobile

      # Cài dependency
      - name: Flutter pub get
        working-directory: mobile
        run: flutter pub get

      # Build APK (debug để khỏi cần ký)
      - name: Build APK (debug)
        working-directory: mobile
        run: flutter build apk --debug

      # Upload file APK để tải về test
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: snp-chatbot-apk
          path: mobile/build/app/outputs/flutter-apk/app-debug.apk
